name: KICS Scan
permissions:
  contents: read
  security-events: write

on:
  push:
    branches: ["master"]
  pull_request:
    branches: ["master"]

jobs:
  kics:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Run KICS
        uses: checkmarx/kics-action@v2.1.16
        with:
          path: .
          output_path: kics-results
          output_formats: "sarif"
          fail_on: high

      - name: Upload SARIF to GitHub
        uses: github/codeql-action/upload-sarif@v3
        with:
          sarif_file: kics-results/results.sarif
